import Head from "next/head";
import Image from "next/image";
import style from "../styles/homepage/page.module.sass"


import {TbPigMoney} from 'react-icons/tb'

export default function Home() {
  return (
    <>
      <Head>
        <title>Finance</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={style.Page}>

        <form className={style.Formulary}>
          <TbPigMoney className={style.Logotype}/>
          <h1>FINANCE</h1>
          <input type="text" placeholder="Email..." />
          <input type="password" placeholder="Password..."/>
          <button className="btn btn-warning">Fazer login</button>
        </form>
      </main>
    </>
  );
}
